### ISSUE TITLE
I don't see the dHealth Network setting in the network variables.

### ISSUE THREAD

**Issue by shimane-ishida** [symbol/symbol-sdk-core-python#6]
I want to send a DHP for dHalthNetwork, but I can't find the dHalthNetwork setting, can you add it for me?

https://github.com/symbol/symbol-sdk-core-python/blob/main/symbolchain/core/sym/Network.py

**Comment by rg911** [comment]
> I want to send a DHP for dHalthNetwork, but I can't find the dHalthNetwork setting, can you add it for me?
> 
> https://github.com/symbol/symbol-sdk-core-python/blob/main/symbolchain/core/sym/Network.py

Don't you there will be a network type for dHealth, since this sdk is for **SYMBOL**

**Comment by 0x6861746366574** [comment]
Hi @shimane-ishida

As @rg911 said, this is an SDK focused on Symbol, a public blockchain protocol. We have no intention to officially support private networks at this time, but you are welcome to fork and adapt as needed. 

Closing this issue as it is not a relevant issue to the SDK.
